# Generated by Django 2.1.3 on 2018-11-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(null=True, verbose_name='popularity'),
        ),
    ]
