# Generated by Django 3.0.3 on 2020-02-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0003_auto_20200214_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='off_identifier',
            field=models.CharField(max_length=200, verbose_name='Identifiant Openfoodfacts'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='openfoodfacts.Category', verbose_name='categorie'),
        ),
    ]
