language: python
python:
  - '3.7'

before_script:
  - pip install pipenv
  - pipenv install

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

script:
  - ./manage.py test