# Generated by Django 3.0.3 on 2020-02-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0002_product_popularity'),
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='origin_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='origin_product', to='openfoodfacts.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='openfoodfacts.Product'),
        ),
    ]
