# Generated by Django 3.0.3 on 2020-02-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openfoodfacts', '0004_auto_20200214_1100'),
        ('favorite', '0002_auto_20200203_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='origin_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_product', to='openfoodfacts.Product', verbose_name='Produit remplacé'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='openfoodfacts.Product', verbose_name='Produit favoris'),
        ),
    ]
