# Generated by Django 3.0.3 on 2020-02-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_auto_20200214_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='origin_product',
        ),
    ]
